name: Apply TASK-004-A1-FIXED (fix route conflict + full-width admin content)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to commit to'
        required: true
        default: 'main'
      commit_message:
        description: 'Commit message'
        required: true
        default: 'TASK-004-A1-FIXED: remove old admin/exhibitions.vue and force full-width admin content'

permissions:
  contents: write

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Fix routes and styles
        run: |
          # 1) Remove old conflicting route file
          rm -f pages/admin/exhibitions.vue || true

          # 2) Overwrite layouts/admin.vue with corrected full-width layout
          cat > layouts/admin.vue << 'VUE'
          <script setup lang="ts">
          const drawer = ref(true)
          const nav = [
            { label: 'Експозиції', to: '/admin/exhibitions', icon: 'mdi-image-multiple' },
            { label: 'Художники',  to: '/admin/artists',     icon: 'mdi-account' },
            { label: 'Квитки',     to: '/admin/tickets',     icon: 'mdi-ticket-confirmation' },
            { label: 'Відгуки',    to: '/admin/reviews',     icon: 'mdi-message-text' },
          ]
          </script>

          <template>
            <div class="admin-wrap">
              <v-navigation-drawer
                v-model="drawer"
                permanent
                color="surface"
                class="admin-drawer"
              >
                <div class="px-4 py-4 text-subtitle-1 font-weight-medium">Адмін-панель</div>
                <v-divider />
                <v-list nav density="comfortable">
                  <v-list-item
                    v-for="item in nav"
                    :key="item.to"
                    :to="item.to"
                    :prepend-icon="item.icon"
                    :title="item.label"
                    rounded
                  />
                </v-list>
              </v-navigation-drawer>

              <div class="admin-content">
                <slot />
              </div>
            </div>
          </template>

          <style>
          .admin-wrap {
            display: grid;
            grid-template-columns: 280px minmax(0, 1fr);
            min-height: calc(100vh - 72px);
          }
          .admin-drawer {
            border-right: 1px solid rgba(0,0,0,0.08);
          }
          .admin-content {
            padding: 24px;
            width: 100%;
            max-width: none;
            min-width: 0;
            overflow: auto;
          }
          @media (max-width: 960px) {
            .admin-wrap { grid-template-columns: 220px minmax(0, 1fr); }
          }
          </style>
          VUE

          # 3) Ensure exhibitions list spans full width (no container max-width)
          if [ -f pages/admin/exhibitions/index.vue ]; then
            # Remove all previous <style scoped> blocks for simplicity and add new one
            sed -i '/<style scoped>/,/<\/style>/d' pages/admin/exhibitions/index.vue
            cat >> pages/admin/exhibitions/index.vue << 'CSS'

<style scoped>
.exh-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 16px;
}
.exh-row {
  cursor: pointer;
}
.v-card.exh-block {
  width: 100%;
  max-width: none;
}
</style>

CSS
          fi

      - name: Commit & push
        run: |
          git config user.name "gallery-bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "${{ github.event.inputs.commit_message }}"
          git push origin HEAD:${{ github.event.inputs.branch }}
