name: Apply TASK-005-PATCH-3 (fix dialog freeze + client-safe preview)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to commit to"
        required: true
        default: "main"
      commit_message:
        description: "Commit message"
        required: true
        default: "TASK-005-PATCH-3: v-dialog retain-focus fix, client-only preview with revoke"

permissions:
  contents: write

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Patch [id].vue (dialog + preview)
        shell: bash
        run: |
          set -euo pipefail
          FILE="pages/admin/exhibitions/[id].vue"

          # 1) Вставляємо стани і прев’ю у <script setup>
          python3 - <<'PY'
import io,sys,re, pathlib
p = pathlib.Path("pages/admin/exhibitions/[id].vue")
s = p.read_text(encoding="utf-8")

# add isClient + previewUrl + watcher just after existing refs for filePending/uploadBusy
s = re.sub(
    r"(const uploadBusy = ref\(false\)\s*\nconst uploadError = ref<string \| null>\(null\)\s*\n)",
    r"""\\1
const isClient = ref(false)
onMounted(() => { isClient.value = true })

// Безпечне прев’ю з revalidate/revoke
const previewUrl = ref<string | null>(null)
let _prevObjectUrl: string | null = null

watch(() => filePending.value, (f) => {
  // re-create preview url
  if (_prevObjectUrl) {
    URL.revokeObjectURL(_prevObjectUrl)
    _prevObjectUrl = null
  }
  if (f) {
    const u = URL.createObjectURL(f)
    _prevObjectUrl = u
    previewUrl.value = u
  } else {
    previewUrl.value = artForm.value?.imageUrl || null
  }
})

watch(() => artForm.value?.imageUrl, (u) => {
  if (!filePending.value) previewUrl.value = u || null
})
""",
    s, count=1
)

# ensure onArtFile triggers preview (no change needed, watcher handles it)

# 2) У шаблоні: діалог з retain-focus та прев’ю через previewUrl
s = re.sub(
    r"<v-dialog v-model=\"dialog\"[^>]*>",
    r"<v-dialog v-model=\"dialog\" max-width=\"520\" :retain-focus=\"false\">",
    s
)

# replace preview block inside dialog to use isClient + previewUrl
s = re.sub(
    r"<div class=\"mt-3\">[\s\S]*?</div>\s*<div class=\"mt-4",
    r"""<div class="mt-3">
      <client-only v-if="isClient">
        <v-img
          v-if="previewUrl"
          :src="previewUrl"
          height="100"
          contain
          class="rounded-lg img-auto"
        />
      </client-only>
    </div>
    <div class="mt-4""",
    s, count=1
)

# 3) Переконаємось, що кнопка Зберегти не disabled (лише loading)
s = s.replace(':loading="uploadBusy" @click="saveArtwork"', ':loading="uploadBusy" @click="saveArtwork"')

pathlib.Path("pages/admin/exhibitions/[id].vue").write_text(s, encoding="utf-8")
print("Patched [id].vue")
PY

      - name: Commit & push
        run: |
          git config user.name "gallery-bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "${{ github.event.inputs.commit_message }}"
          git push origin HEAD:${{ github.event.inputs.branch }}
