name: Export Repo as ZIP

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch or tag to export"
        required: true
        default: "main"

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Archive repository
        run: |
          zip -r repo_export.zip . -x ".git/*" ".github/workflows/export_repo_zip.yml"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: repo_export
          path: repo_export.zip
          if-no-files-found: error
